# define variables
## CMN
CMN_RGSTR_SVR_=dflt # 'docker.io'
DKH_RGSTR_SVR_='docker.io'
VM_IMG_TAG_SFX_=${VM_IMG_TAG_SFX_:-7.9.2009}
VM_IMG_TAG_=centos${VM_IMG_TAG_SFX_}
## BASE
APPVM_BASE_SRC_IMG_NM_=centos
APPVM_BASE_SRC_IMG_TG_=${VM_IMG_TAG_SFX_}
APPVM_BASE_IMG_NM_=korabo/appvm-base
APPVM_BASE_IMG_TG_=${VM_IMG_TAG_}
## LAMPX
DVLVM_LAMPX_SRC_IMG_NM_=${APPVM_BASE_IMG_NM_}
DVLVM_LAMPX_SRC_IMG_TG_=${APPVM_BASE_IMG_TG_}
DVLVM_LAMPX_IMG_NM_=korabo/dvlvm-lampx
DVLVM_LAMPX_IMG_TG_=${VM_IMG_TAG_}
### LAMPX:SYS VERSION
DVLVM_LAMPX_SYS_PYTV_=38
DVLVM_LAMPX_SYS_PHPV_=80
DVLVM_LAMPX_SYS_NODEV_=14
DVLVM_LAMPX_SYS_JAVAV_=11
## USER
DVLVM_USER_SRC_IMG_NM_=${DVLVM_LAMPX_IMG_NM_}
DVLVM_USER_SRC_IMG_TG_=${DVLVM_LAMPX_SRC_IMG_TG_}
DVLVM_USER_IMG_NM_=korabo/dvlvm-user
DVLVM_USER_IMG_TG_=${VM_IMG_TAG_}
### USER: USER CONF
DVLVM_USER_SUDR_GID_=500
DVLVM_USER_SUDR_GNM_=dvlsudoers
DVLVM_USER_USER_GID_=1000
DVLVM_USER_USER_GNM_=dvladmin
DVLVM_USER_USER_UID_=1000
DVLVM_USER_DVLVM_USER_USER_NAM_=dvladmin
DVLVM_USER_USER_PSW_=dvladmin
DVLVM_USER_ALTUSERS_='dvlusr1,dvlusr2,dvlusr3,dvlusr4,dvlusr5'
