version: "3"

services:
  dev-web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DK_IMG: korabo/dvlvm-lampx-user
        DK_TAG: centos7.9.2009
    hostname: 'dev-web-local'
    # sysctls:
    #   fs.inotify.max_user_watches: 524288
    volumes:
      - ../home_dvladmin/source:/home/dvladmin/source:rw
      - ../home_zshare:/home/zshare:rw
#      - ~/.gitconfig:/root/.gitconfig
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      # - 0.0.0.0:60080:80
      # - 0.0.0.0:60443:443
#    command: sleep infinity
# DSN: mysql:host=dev-db;dbname=scaru;charset=utf8
# https://qiita.com/dyoshikawa/items/05d627b962da35f7d5b6
