# busybox for data storage container

# From Local
FROM busybox

USER root

# create storea dirs
ARG PV_LST="/opt/var/lib/mysql /opt/share /opt/home /opt/var/log /opt/var/www /opt/smtp4dev /opt/etc /opt/usr_local_etc"
RUN  \
for d in ${PV_LST};do \
    mkdir -p $d; \
    chmod -R 0777 $d; \
done


ENTRYPOINT ["/bin/true"]

LABEL MAINTAINER="S.TAKEUCHI(KRB/SPG)" \
    version="1.0.0" updated="20220621" containerid="storage"
